services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./backend
          ignore:
            - node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "4000:80"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
    depends_on:
      - backend